### ISSUE TITLE
TypeError: Object [object Object] has no method 'Maybe'

### ISSUE THREAD

**Issue by kaiyes** [Lepozepo/cloudinary#92] opened 2016-07-19 18:10 UTC
Anyone has this error ? 

full error looks like this. I am using another cloudianry package successfully though. So kinda lost here,

![screen shot 2016-07-20 at 12 08 58 am](https://cloud.githubusercontent.com/assets/5293742/16961196/483aee36-4e0e-11e6-8550-b76d89a3deab.png)

**Comment by Lepozepo** [comment] 2016-07-19 18:11
Hey! The issue is your version of `Match`, I need to patch `Maybe` with `Optional` to make it compatible with previous versions of Meteor

**Comment by Sntax** [comment] 2016-08-02 12:41
Yup - running into the same issue here. Thanks for the great work so far @Lepozepo.

**Comment by Lepozepo** [comment] 2016-08-06 14:57
This should be fixed in the latest version ^_^

**Closed by Lepozepo** 2016-08-06 14:57 UTC
Labels: bug

**Comment by kaiyes** [comment] 2016-08-06 17:10
Thanks a lot mate

**Comment by jessylachapelle** [comment] 2016-08-06 17:13
Thank you, sorry I wanted to do a PR, but I was swamped :(
